# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import os
from collections.abc import AsyncIterator
from contextlib import asynccontextmanager

import google.auth
from a2a.server.apps import A2AFastAPIApplication
from a2a.server.request_handlers import DefaultRequestHandler
from a2a.server.tasks import InMemoryTaskStore
from a2a.types import AgentCapabilities, AgentCard, AgentProvider
from a2a.utils.constants import (
    AGENT_CARD_WELL_KNOWN_PATH,
    EXTENDED_AGENT_CARD_PATH,
)
from fastapi import FastAPI
from google.adk.a2a.utils.agent_card_builder import AgentCardBuilder
from google.adk.artifacts import GcsArtifactService, InMemoryArtifactService
from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService
from google.cloud import logging as google_cloud_logging

from app.agent import app as adk_app
from app.a2ui_executor import A2UIAgentExecutor
from app.app_utils.telemetry import setup_telemetry
from app.app_utils.typing import Feedback

setup_telemetry()
_, project_id = google.auth.default()
logging_client = google_cloud_logging.Client()
logger = logging_client.logger(__name__)

# Artifact bucket for ADK (created by Terraform, passed via env var)
logs_bucket_name = os.environ.get("LOGS_BUCKET_NAME")
artifact_service = (
    GcsArtifactService(bucket_name=logs_bucket_name)
    if logs_bucket_name
    else InMemoryArtifactService()
)

runner = Runner(
    app=adk_app,
    artifact_service=artifact_service,
    session_service=InMemorySessionService(),
)

request_handler = DefaultRequestHandler(
    agent_executor=A2UIAgentExecutor(runner=runner), task_store=InMemoryTaskStore()
)

A2A_RPC_PATH = f"/a2a/{adk_app.name}"


async def build_dynamic_agent_card() -> AgentCard:
    """Builds the Agent Card dynamically from the root_agent.

    The ADK AgentCardBuilder auto-generates skills from the agent definition,
    but it dumps the full system prompt into the root skill description.
    We post-process the card to keep the root skill concise for A2A discovery
    while preserving the auto-generated tool skills as-is.
    """
    agent_card_builder = AgentCardBuilder(
        agent=adk_app.root_agent,
        capabilities=AgentCapabilities(streaming=True),
        rpc_url=f"{os.getenv('APP_URL', 'http://0.0.0.0:8000')}{A2A_RPC_PATH}",
        agent_version=os.getenv("AGENT_VERSION", "1.0.0"),
        provider=AgentProvider(
            organization="Cloud Demo Engineering",
            url="https://github.com/GoogleCloudPlatform",
        ),
    )
    agent_card = await agent_card_builder.build()
    agent_card.icon_url = (
        "https://storage.googleapis.com/fabricofuint_organic_living_assets/agent-icons/G-BW-GemEnt.jpg"
    )

    # --- Post-process: fix the root skill generated by the builder ---
    for skill in agent_card.skills:
        if skill.id == adk_app.root_agent.name:
            skill.name = "Product Strategy Analyst"
            skill.description = (
                "Generates executive-ready product strategy reports with "
                "AI-powered video content creation. Analyzes market data, "
                "provides pricing and portfolio recommendations, and exports "
                "formatted reports to Google Drive."
            )
            skill.examples = [
                "Create a strategic report for our new collection launch",
                "Generate campaign videos for the product line",
                "Analyze pricing strategy and export to Google Docs",
            ]
            break

    return agent_card


@asynccontextmanager
async def lifespan(app_instance: FastAPI) -> AsyncIterator[None]:
    agent_card = await build_dynamic_agent_card()
    a2a_app = A2AFastAPIApplication(agent_card=agent_card, http_handler=request_handler)
    a2a_app.add_routes_to_app(
        app_instance,
        agent_card_url=AGENT_CARD_WELL_KNOWN_PATH,
        rpc_url=A2A_RPC_PATH,
        extended_agent_card_url=EXTENDED_AGENT_CARD_PATH,
    )
    yield


app = FastAPI(
    title="Product Strategy Agent",
    description="API for interacting with the Agent Product Strategy",
    lifespan=lifespan,
)


@app.post("/feedback")
def collect_feedback(feedback: Feedback) -> dict[str, str]:
    """Collect and log feedback.

    Args:
        feedback: The feedback data to log

    Returns:
        Success message
    """
    logger.log_struct(feedback.model_dump(), severity="INFO")
    return {"status": "success"}


# Main execution
if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="0.0.0.0", port=8000)
